//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourFirmGavrilov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public Nullable<int> customersId { get; set; }
        public Nullable<int> tourId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
